steps:
  # Print the branch name
  - id: 'branch-name'
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building from branch: $BRANCH_NAME"

  # Install dependencies for all services
  - id: 'install-dependencies'
    name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies for all services..."
        cd backend && npm ci; cd ..
        cd frontend && npm ci; cd ..
        cd image-processor && npm ci; cd ..

  # Build backend
  - id: 'build-backend'
    name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building backend..."
        cd backend
        npm run build

  # Build frontend
  - id: 'build-frontend'
    name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building frontend..."
        cd frontend
        npm run build

  # Build image processor
  - id: 'build-image-processor'
    name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building image processor..."
        cd image-processor
        npm run build
        # Create a directory for the deployable
        mkdir -p /workspace/deployables/image-processor
        # Copy necessary files for deployment
        cp -r dist package.json package-lock.json /workspace/deployables/image-processor/

  # Create Cloud Function source archive
  - id: 'create-function-archive'
    name: 'debian:bullseye-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating Cloud Function source archive..."
        # Install zip package
        apt-get update && apt-get install -y zip

        cd /workspace/deployables/image-processor
        zip -r ${_IMAGE_PROCESSOR_NAME}-source.zip .
        mkdir -p /workspace/artifacts
        cp ${_IMAGE_PROCESSOR_NAME}-source.zip /workspace/artifacts/

  # Create GCS bucket if it doesn't exist and upload function archive
  - id: 'create-bucket-and-upload'
    name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Check if bucket exists, create it if it doesn't
        if ! gsutil ls -b gs://gcf-sources-${PROJECT_ID}-${_REGION} &>/dev/null; then
          echo "Creating bucket gs://gcf-sources-${PROJECT_ID}-${_REGION}..."
          gsutil mb -l ${_REGION} gs://gcf-sources-${PROJECT_ID}-${_REGION}
        else
          echo "Bucket gs://gcf-sources-${PROJECT_ID}-${_REGION} already exists."
        fi

        # Upload the function source archive
        echo "Uploading ${_IMAGE_PROCESSOR_NAME}-source.zip to bucket..."
        gsutil cp /workspace/artifacts/${_IMAGE_PROCESSOR_NAME}-source.zip gs://gcf-sources-${PROJECT_ID}-${_REGION}/${_IMAGE_PROCESSOR_NAME}-source.zip

  # Build and push backend container
  - id: 'build-push-backend'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_BACKEND_SERVICE_NAME}-${_ENVIRONMENT}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_BACKEND_SERVICE_NAME}-${_ENVIRONMENT}:latest'
      - './backend'

  # Build and push frontend container
  - id: 'build-push-frontend'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_FRONTEND_SERVICE_NAME}-${_ENVIRONMENT}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_FRONTEND_SERVICE_NAME}-${_ENVIRONMENT}:latest'
      - './frontend'

  # Push backend container
  - id: 'push-backend'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_BACKEND_SERVICE_NAME}-${_ENVIRONMENT}:${SHORT_SHA}'

  # Push frontend container
  - id: 'push-frontend'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_FRONTEND_SERVICE_NAME}-${_ENVIRONMENT}:${SHORT_SHA}'

  # Push latest tags
  - id: 'push-latest-tags'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_BACKEND_SERVICE_NAME}-${_ENVIRONMENT}:latest'

  - id: 'push-latest-tags-frontend'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_FRONTEND_SERVICE_NAME}-${_ENVIRONMENT}:latest'

# Images to be pushed to the container registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_BACKEND_SERVICE_NAME}-${_ENVIRONMENT}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_BACKEND_SERVICE_NAME}-${_ENVIRONMENT}:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_FRONTEND_SERVICE_NAME}-${_ENVIRONMENT}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_FRONTEND_SERVICE_NAME}-${_ENVIRONMENT}:latest'

# Substitution variables
substitutions:
  _REGION: 'us-east4'
  _ENVIRONMENT: 'dev'
  _BACKEND_SERVICE_NAME: 'full-stack-webapp-backend'
  _FRONTEND_SERVICE_NAME: 'full-stack-webapp-frontend'
  _IMAGE_PROCESSOR_NAME: 'generate-thumbnail'

# Timeout for the build (30 minutes)
timeout: '1800s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
